In [4]:
import pandas as pd
import numpy as np

In [6]:
flight_details= pd.read_csv("/PNRB-ZZ-20231208_062017.csv")
passenger= pd.read_csv("/PNRP-ZZ-20231208_111136.csv")
schedule=pd.read_csv("/SCH-ZZ-20231208_035117.csv")
# flight_details

In [7]:
#input

specific_schedule_id= "SCH-ZZ-9117133"
specific_date="20240403"

In [14]:
# segment score and pax score input

external_multiplier_seg = 100
external_multiplier_pax = 50

In [15]:
#ssr cost input and loyalty cost

tags_cost ={'INFT' : 200, 'WCHR' : 200, 'WCHS' : 200, 'WCHC' : 200, 'LANG' : 200, 'CHLD' : 200, 'MAAS' : 200, 'UNMR' : 200, 'BLND' : 200, 'DEAF' : 200, 'EXST' : 200, 'MEAL' : 200, 'NSST' : 200, 'NRPS' : 200,  }
loyalty_cost = {'Platinum' : 2000, 'Gold' : 2000, 'Silver' : 2000, 'none':0 }

In [16]:
tag_columns = ['SPECIAL_NAME_CD2', 'SSR_CODE_CD1']

In [11]:
#generating departure key from input

schedule['FlightNumber']=schedule['FlightNumber'].astype(int)
selected_rows = schedule[schedule['ScheduleID'] == specific_schedule_id][['ScheduleID', 'CarrierCode', 'ArrivalAirport', 'DepartureAirport', 'FlightNumber']]
selected_rows['FlightNumber'] = selected_rows['FlightNumber'].astype(str)
selected_rows['Concatenated'] = selected_rows[['DepartureAirport', 'ArrivalAirport', 'FlightNumber']].astype(str).apply(lambda x: ''.join(x), axis=1)
selected_rows['Concatenated'] = specific_date+selected_rows['Concatenated'].replace(' ', '', regex=True)
selected_rows['Concatenated'] = selected_rows[['CarrierCode','Concatenated']].astype(str).apply(lambda x: ''.join(x), axis=1)
specific_dep_key= selected_rows.at[selected_rows.index[0], "Concatenated"]
flight_details["DEP_KEY"]=flight_details["DEP_KEY"].astype(str)
# selected_rows

In [12]:
filtered_f= flight_details[flight_details["DEP_KEY"]== specific_dep_key]
filtered_f_copy= filtered_f
filtered_f_copy

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ
0,DRGS80,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,4,3,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
1,YEZQ47,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,2,4,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
2,JDDM40,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,3,2,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
3,AVFF16,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,4,1,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
4,DBLE79,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,2,2,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,WJIM84,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1,4,6,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
78,GYKM90,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1,2,4,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
79,JGYU67,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1,1,4,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
80,OQHS47,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1,4,1,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47
81,JMZZ69,03-02-2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1,4,1,ZZ,2504,BLR,CCU,04-03-2024,04-03-2024 15:35,04-03-2024 18:17,04-03-2024 10:05,04-03-2024 12:47

In [ ]:
filtered_f_copy['SEG_TOTAL_MULTIPLIED'] = filtered_f_copy['SEG_TOTAL'] * external_multiplier_seg
filtered_f_copy['PAX_CNT_MULTIPLIED'] = filtered_f_copy['PAX_CNT'] * external_multiplier_pax

# Create a new column with the sum of SEG_SEQ_MULTIPLIED and PAX_CNT_MULTIPLIED
filtered_f_copy['SUM_SEG_PAX'] = filtered_f_copy['SEG_TOTAL_MULTIPLIED'] + filtered_f_copy['PAX_CNT_MULTIPLIED']

In [20]:
reclocs_list = filtered_f["RECLOC"].tolist()
filtered_passengers_list = passenger[passenger["RECLOC"].isin(reclocs_list)]
filtered_passengers_list['ssr_score'] = filtered_passengers_list[tag_columns].applymap(tags_cost.get).sum(axis=1)
filtered_passengers_list['Loyalty_score'] = filtered_passengers_list['TierLevel'].map(loyalty_cost).fillna(loyalty_cost['none'])

filtered_passengers_list['Total_score'] = filtered_passengers_list['Loyalty_score'] + filtered_passengers_list['ssr_score']
sorted_passengers=filtered_passengers_list.sort_values(by="Total_score", ascending=False)

# filtered_passengers_list
sorted_passengers

<ipython-input-20-c132944055e9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['ssr_score'] = filtered_passengers_list[tag_columns].applymap(tags_cost.get).sum(axis=1)
<ipython-input-20-c132944055e9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['Loyalty_score'] = filtered_passengers_list['TierLevel'].map(loyalty_cost).fillna(loyalty_cost['none'])
<ipython-input-20-c132944055e9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['Total_score'] = filtered_passengers_list['Loyalty_score'] + filtered_passengers_list['ssr_score']

,RECLOC,CREATION_DTZ,CUSTOMER_ID,LAST_NAME,FIRST_NAME,NATIONALITY,DOB,CONTACT_PH_NUM,CONTACT_EMAIL,DOC_TYPE,DOC_ID,SPECIAL_NAME_CD2,SSR_CODE_CD1,SPECIAL_NAME_CD1,FF_NUM,TierLevel,ssr_score,Loyalty_score,Total_score
288,JGYU67,03-02-2024 16:35,YPD1979,Roy,Jayesh,IN,02-03-2020,(733) 611-1023,jayeshroy1@example.com,Passport,4.141344e+08,NRPS,WCHR,INF,1.139845e+09,Platinum,400.0,2000.0,2400.0
88,ZGKM38,03-02-2024 16:35,SBJ2204,Kohli,Tiya,IN,5/13/2020,(651) 908-4960,tiyakohli1@example.com,Passport,8.567387e+08,NaN,WCHR,INF,6.905164e+09,Silver,200.0,2000.0,2200.0
70,YNIO33,03-02-2024 16:35,PJV3164,Harris,Rebecca,US,07-08-2000,(403) 824-3750,rebeccaharris2@example.com,Driving License,2.060000e+11,NRPS,NaN,ADT,4.329324e+09,Gold,200.0,2000.0,2200.0
170,UPIA63,03-02-2024 16:35,HUF2131,Lee,Patricia,CA,12/24/1945,(897) 834-1040,patricialee6@example.com,Driving License,8.690000e+11,NaN,DEAF,S65,8.891542e+09,Gold,200.0,2000.0,2200.0
83,IMFV13,03-02-2024 16:35,ZXD6227,Barman,Inaaya,IN,09-12-1964,(876) 747-1359,inaaya barman2@example.com,Govt-Id,4.640398e+08,NRPS,NaN,ADT,7.051805e+09,Gold,200.0,2000.0,2200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,KCKH36,03-02-2024 16:35,KGY5115,Rhodes,Sherri,CA,4/21/2013,(515) 973-3160,sherrirhodes1@example.com,Passport,8.280000e+11,NRSA,NaN,CHD,NaN,NaN,0.0,0.0,0.0
169,UPIA63,03-02-2024 16:35,VJB4003,Singh,Jasmin,CA,1/15/1969,(882) 757-8061,jasminsingh5@example.com,Govt-Id,1.138792e+09,NaN,NaN,ADT,NaN,NaN,0.0,0.0,0.0
54,YFWB74,03-02-2024 16:35,XOY7883,Singleton,Kristen,CA,8/16/2019,(724) 985-3357,kristensingleton1@example.com,Govt-Id,4.730588e+09,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
55,IDKP89,03-02-2024 16:35,MLA7169,Carroll,Tamara,US,9/13/1948,(683) 616-7605,tamaracarroll1@example.com,Driving License,7.150000e+11,NaN,NaN,S65,NaN,NaN,0.0,0.0,0.0
204,DMDN53,03-02-2024 16:35,LQN8035,Chana,Prisha,IN,2/21/1939,(245) 639-4839,prishachana3@example.com,Driving License,3.880000e+11,NaN,NaN,S65,NaN,NaN,0.0,0.0,0.0

In [24]:
merged_sorted_passengers = sorted_passengers.groupby('RECLOC')['Total_score'].sum().reset_index()
# merged_sorted_passengers
merged_table = pd.merge(merged_sorted_passengers, filtered_f_copy, on='RECLOC', how='outer')
merged_table['final_score'] = merged_table['Total_score'] + merged_table['SUM_SEG_PAX']
merged_table

KeyError: ignored

KeyError: ignored