In [96]:
import pandas as pd
import numpy as np

In [98]:
f=pd.read_csv('/INV-ZZ-20231208_041852.csv')

f = pd.read_csv('/INV-ZZ-20231208_041852.csv')

In [99]:
f.isna().sum()

InventoryId              0
ScheduleId               0
CarrierCode              0
Dep_Key                  0
FlightNumber             0
AircraftType             0
DepartureDate            0
DepartureDateTime        0
ArrivalDateTime          0
DepartureAirport         0
ArrivalAirport           0
TotalCapacity            0
TotalInventory           0
BookedInventory          0
Oversold                 0
AvailableInventory       0
FirstClass               0
BusinessClass            0
PremiumEconomyClass      0
EconomyClass             0
FC_TotalInventory        0
FC_BookedInventory       0
FC_Oversold              0
FC_AvailableInventory    0
BC_TotalInventory        0
BC_BookedInventory       0
BC_Oversold              0
BC_AvailableInventory    0
PC_TotalInventory        0
PC_BookedInventory       0
PC_Oversold              0
PC_AvailableInventory    0
EC_TotalInventory        0
EC_BookedInventory       0
EC_Oversold              0
EC_AvailableInventory    0
FC_CD                    0
BC_CD                    0
PC_CD                    0
EC_CD                    0
dtype: int64

f = pd.read_csv('/INV-ZZ-20231208_041852.csv')

f.isna().sum()

In [ ]:
f.isna().sum()

InventoryId              0
ScheduleId               0
CarrierCode              0
Dep_Key                  0
FlightNumber             0
AircraftType             0
DepartureDate            0
DepartureDateTime        0
ArrivalDateTime          0
DepartureAirport         0
ArrivalAirport           0
TotalCapacity            0
TotalInventory           0
BookedInventory          0
Oversold                 0
AvailableInventory       0
FirstClass               0
BusinessClass            0
PremiumEconomyClass      0
EconomyClass             0
FC_TotalInventory        0
FC_BookedInventory       0
FC_Oversold              0
FC_AvailableInventory    0
BC_TotalInventory        0
BC_BookedInventory       0
BC_Oversold              0
BC_AvailableInventory    0
PC_TotalInventory        0
PC_BookedInventory       0
PC_Oversold              0
PC_AvailableInventory    0
EC_TotalInventory        0
EC_BookedInventory       0
EC_Oversold              0
EC_AvailableInventory    0
FC_CD                    0
BC_CD                    0
PC_CD                    0
EC_CD                    0
dtype: int64

In [100]:
f

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
0,INV-ZZ-2774494,SCH-ZZ-3400127,ZZ,ZZ20240505AMDHYD2223.0,2223.0,Boeing 777,05/05/2024,2024-05-05 10:52:00,2024-05-05 19:30:00,AMD,...,49,74,199,102,68,97,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
1,INV-ZZ-8029879,SCH-ZZ-3400127,ZZ,ZZ20240506AMDHYD2223.0,2223.0,Boeing 777,05/06/2024,2024-05-06 10:52:00,2024-05-06 19:30:00,AMD,...,47,72,202,106,64,96,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
2,INV-ZZ-6852033,SCH-ZZ-3400127,ZZ,ZZ20240507AMDHYD2223.0,2223.0,Boeing 777,05/07/2024,2024-05-07 10:52:00,2024-05-07 19:30:00,AMD,...,44,61,197,114,56,83,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
3,INV-ZZ-7065859,SCH-ZZ-3400127,ZZ,ZZ20240508AMDHYD2223.0,2223.0,Boeing 777,05/08/2024,2024-05-08 10:52:00,2024-05-08 19:30:00,AMD,...,51,66,192,103,67,89,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
4,INV-ZZ-1595392,SCH-ZZ-3400127,ZZ,ZZ20240512AMDHYD2223.0,2223.0,Boeing 777,05/12/2024,2024-05-12 10:52:00,2024-05-12 19:30:00,AMD,...,48,66,197,107,63,90,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2007,INV-ZZ-6129434,SCH-ZZ-9762124,ZZ,ZZ20240617GAUPNQ3440.0,3440.0,Boeing 757,06/17/2024,2024-06-17 15:57:00,2024-06-18 05:13:00,GAU,...,29,37,96,45,38,51,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
2008,INV-ZZ-2755720,SCH-ZZ-9762124,ZZ,ZZ20240620GAUPNQ3440.0,3440.0,Boeing 757,06/20/2024,2024-06-20 15:57:00,2024-06-21 05:13:00,GAU,...,29,39,93,43,40,50,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
2009,INV-ZZ-2707415,SCH-ZZ-9762124,ZZ,ZZ20240621GAUPNQ3440.0,3440.0,Boeing 757,06/21/2024,2024-06-21 15:57:00,2024-06-22 05:13:00,GAU,...,31,40,93,40,43,53,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
2010,INV-ZZ-1293533,SCH-ZZ-9762124,ZZ,ZZ20240623GAUPNQ3440.0,3440.0,Boeing 757,06/23/2024,2024-06-23 15:57:00,2024-06-24 05:13:00,GAU,...,29,41,98,43,40,55,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
2011,INV-ZZ-1560576,SCH-ZZ-9762124,ZZ,ZZ20240624GAUPNQ3440.0,3440.0,Boeing 757,06/24/2024,2024-06-24 15:57:00,2024-06-25 05:13:00,GAU,...,34,42,99,40,43,59,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."

In [101]:
f.columns

Index(['InventoryId', 'ScheduleId', 'CarrierCode', 'Dep_Key', 'FlightNumber',
       'AircraftType', 'DepartureDate', 'DepartureDateTime', 'ArrivalDateTime',
       'DepartureAirport', 'ArrivalAirport', 'TotalCapacity', 'TotalInventory',
       'BookedInventory', 'Oversold', 'AvailableInventory', 'FirstClass',
       'BusinessClass', 'PremiumEconomyClass', 'EconomyClass',
       'FC_TotalInventory', 'FC_BookedInventory', 'FC_Oversold',
       'FC_AvailableInventory', 'BC_TotalInventory', 'BC_BookedInventory',
       'BC_Oversold', 'BC_AvailableInventory', 'PC_TotalInventory',
       'PC_BookedInventory', 'PC_Oversold', 'PC_AvailableInventory',
       'EC_TotalInventory', 'EC_BookedInventory', 'EC_Oversold',
       'EC_AvailableInventory', 'FC_CD', 'BC_CD', 'PC_CD', 'EC_CD'],
      dtype='object')

In [102]:
def flights_between(departure_airport,arrival_airport,flight_schedule_df):
    filtered_flights = flight_schedule_df[
        (flight_schedule_df['DepartureAirport'] == departure_airport) &
        (flight_schedule_df['ArrivalAirport'] == arrival_airport)
    ]
    return filtered_flights

In [103]:
(flights_between('BLR','HYD',f))

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
99,INV-ZZ-6519240,SCH-ZZ-8346723,ZZ,ZZ20240417BLRHYD3027.0,3027.0,BAe 146,04/17/2024,2024-04-17 18:48:00,2024-04-18 02:58:00,BLR,...,9,13,43,25,11,18,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
100,INV-ZZ-6268317,SCH-ZZ-8346723,ZZ,ZZ20240418BLRHYD3027.0,3027.0,BAe 146,04/18/2024,2024-04-18 18:48:00,2024-04-19 02:58:00,BLR,...,8,12,43,27,9,16,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
101,INV-ZZ-1078045,SCH-ZZ-8346723,ZZ,ZZ20240419BLRHYD3027.0,3027.0,BAe 146,04/19/2024,2024-04-19 18:48:00,2024-04-20 02:58:00,BLR,...,10,14,41,23,13,18,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
102,INV-ZZ-3057117,SCH-ZZ-8346723,ZZ,ZZ20240424BLRHYD3027.0,3027.0,BAe 146,04/24/2024,2024-04-24 18:48:00,2024-04-25 02:58:00,BLR,...,9,14,42,24,12,18,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
103,INV-ZZ-2798091,SCH-ZZ-8346723,ZZ,ZZ20240425BLRHYD3027.0,3027.0,BAe 146,04/25/2024,2024-04-25 18:48:00,2024-04-26 02:58:00,BLR,...,10,15,43,23,13,20,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
104,INV-ZZ-9324665,SCH-ZZ-8346723,ZZ,ZZ20240426BLRHYD3027.0,3027.0,BAe 146,04/26/2024,2024-04-26 18:48:00,2024-04-27 02:58:00,BLR,...,9,14,40,23,13,17,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
105,INV-ZZ-2960204,SCH-ZZ-8346723,ZZ,ZZ20240501BLRHYD3027.0,3027.0,BAe 146,05/01/2024,2024-05-01 18:48:00,2024-05-02 02:58:00,BLR,...,10,14,41,22,14,19,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
106,INV-ZZ-8230417,SCH-ZZ-8346723,ZZ,ZZ20240502BLRHYD3027.0,3027.0,BAe 146,05/02/2024,2024-05-02 18:48:00,2024-05-03 02:58:00,BLR,...,10,15,43,23,13,20,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
107,INV-ZZ-6020989,SCH-ZZ-8346723,ZZ,ZZ20240503BLRHYD3027.0,3027.0,BAe 146,05/03/2024,2024-05-03 18:48:00,2024-05-04 02:58:00,BLR,...,9,13,41,24,12,17,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
108,INV-ZZ-8076572,SCH-ZZ-8346723,ZZ,ZZ20240508BLRHYD3027.0,3027.0,BAe 146,05/08/2024,2024-05-08 18:48:00,2024-05-09 02:58:00,BLR,...,10,14,43,23,13,20,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
109,INV-ZZ-4625808,SCH-ZZ-8346723,ZZ,ZZ20240509BLRHYD3027.0,3027.0,BAe 146,05/09/2024,2024-05-09 18:48:00,2024-05-10 02:58:00,BLR,...,11,16,42,21,15,21,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
110,INV-ZZ-6914909,SCH-ZZ-8346723,ZZ,ZZ20240510BLRHYD3027.0,3027.0,BAe 146,05/10/2024,2024-05-10 18:48:00,2024-05-11 02:58:00,BLR,...,11,14,43,22,14,21,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
111,INV-ZZ-6253561,SCH-ZZ-8346723,ZZ,ZZ20240515BLRHYD3027.0,3027.0,BAe 146,05/15/2024,2024-05-15 18:48:00,2024-05-16 02:58:00,BLR,...,9,14,41,23,13,18,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
112,INV-ZZ-3044078,SCH-ZZ-8346723,ZZ,ZZ20240516BLRHYD3027.0,3027.0,BAe 146,05/16/2024,2024-05-16 18:48:00,2024-05-17 02:58:00,BLR,...,11,15,40,21,15,19,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
113,INV-ZZ-4758929,SCH-ZZ-8346723,ZZ,ZZ20240517BLRHYD3027.0,3027.0,BAe 146,05/17/2024,2024-05-17 18:48:00,2024-05-18 02:58:00,BLR,...,12,16,43,21,15,22,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
114,INV-ZZ-5742444,SCH-ZZ-8346723,ZZ,ZZ20240522BLRHYD3027.0,3027.0,BAe 146,05/22/2024,2024-05-22 18:48:00,2024-05-23 02:58:00,BLR,...,12,16,41,20,16,21,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
115,INV-ZZ-4541543,SCH-ZZ-8346723,ZZ,ZZ20240523BLRHYD3027.0,3027.0,BAe 146,05/23/2024,2024-05-23 18:48:00,2024-05-24 02:58:00,BLR,...,12,17,42,20,16,22,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
116,INV-ZZ-7541312,SCH-ZZ-8346723,ZZ,ZZ20240524BLRHYD3027.0,3027.0,BAe 146,05/24/2024,2024-05-24 18:48:00,2024-05-25 02:58:00,BLR,...,13,17,43,20,16,23,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
117,INV-ZZ-3758978,SCH-ZZ-8346723,ZZ,ZZ20240529BLRHYD3027.0,3027.0,BAe 146,05/29/2024,2024-05-29 18:48:00,2024-05-30 02:58:00,BLR,...,10,15,40,21,15,19,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
118,INV-ZZ-9399965,SCH-ZZ-8346723,ZZ,ZZ20240530BLRHYD3027.0,3027.0,BAe 146,05/30/2024,2024-05-30 18:48:00,2024-05-31 02:58:00,BLR,...,12,15,43,21,15,22,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
119,INV-ZZ-4666534,SCH-ZZ-8346723,ZZ,ZZ20240531BLRHYD3027.0,3027.0,BAe 146,05/31/2024,2024-05-31 18:48:00,2024-06-01 02:58:00,BLR,...,12,17,43,21,15,22,"{'F': 5, 'P': 4}","{'C': 7, 'J': 5, 'Z': 5}","{'Q': 8, 'R': 5, 'S': 3, 'T': 3, 'H': 5, 'M': 3}","{'Y': 3, 'A': 3, 'B': 1, 'D': 1, 'E': 1, 'G': ..."
716,INV-ZZ-5889973,SCH-ZZ-4295870,ZZ,ZZ20240503BLRHYD2811.0,2811.0,Boeing 717,05/03/2024,2024-05-03 14:16:00,2024-05-04 07:15:00,BLR,...,10,16,46,25,15,21,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
717,INV-ZZ-2392716,SCH-ZZ-4295870,ZZ,ZZ20240504BLRHYD2811.0,2811.0,Boeing 717,05/04/2024,2024-05-04 14:16:00,2024-05-05 07:15:00,BLR,...,10,16,48,27,13,21,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
718,INV-ZZ-7763907,SCH-ZZ-4295870,ZZ,ZZ20240507BLRHYD2811.0,2811.0,Boeing 717,05/07/2024,2024-05-07 14:16:00,2024-05-08 07:15:00,BLR,...,11,16,48,26,14,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
719,INV-ZZ-9176409,SCH-ZZ-4295870,ZZ,ZZ20240510BLRHYD2811.0,2811.0,Boeing 717,05/10/2024,2024-05-10 14:16:00,2024-05-11 07:15:00,BLR,...,12,17,44,22,18,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
720,INV-ZZ-3080843,SCH-ZZ-4295870,ZZ,ZZ20240511BLRHYD2811.0,2811.0,Boeing 717,05/11/2024,2024-05-11 14:16:00,2024-05-12 07:15:00,BLR,...,13,16,46,24,16,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
721,INV-ZZ-7721018,SCH-ZZ-4295870,ZZ,ZZ20240514BLRHYD2811.0,2811.0,Boeing 717,05/14/2024,2024-05-14 14:16:00,2024-05-15 07:15:00,BLR,...,13,17,45,22,18,23,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
722,INV-ZZ-5634659,SCH-ZZ-4295870,ZZ,ZZ20240517BLRHYD2811.0,2811.0,Boeing 717,05/17/2024,2024-05-17 14:16:00,2024-05-18 07:15:00,BLR,...,13,18,47,23,17,24,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
723,INV-ZZ-9873963,SCH-ZZ-4295870,ZZ,ZZ20240518BLRHYD2811.0,2811.0,Boeing 717,05/18/2024,2024-05-18 14:16:00,2024-05-19 07:15:00,BLR,...,13,18,48,23,17,25,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
724,INV-ZZ-2253993,SCH-ZZ-4295870,ZZ,ZZ20240521BLRHYD2811.0,2811.0,Boeing 717,05/21/2024,2024-05-21 14:16:00,2024-05-22 07:15:00,BLR,...,14,17,46,22,18,24,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
725,INV-ZZ-6802261,SCH-ZZ-4295870,ZZ,ZZ20240524BLRHYD2811.0,2811.0,Boeing 717,05/24/2024,2024-05-24 14:16:00,2024-05-25 07:15:00,BLR,...,14,19,48,22,18,26,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
726,INV-ZZ-8926917,SCH-ZZ-4295870,ZZ,ZZ20240525BLRHYD2811.0,2811.0,Boeing 717,05/25/2024,2024-05-25 14:16:00,2024-05-26 07:15:00,BLR,...,11,17,46,24,16,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
727,INV-ZZ-3650861,SCH-ZZ-4295870,ZZ,ZZ20240528BLRHYD2811.0,2811.0,Boeing 717,05/28/2024,2024-05-28 14:16:00,2024-05-29 07:15:00,BLR,...,13,19,48,22,18,26,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
728,INV-ZZ-6703142,SCH-ZZ-4295870,ZZ,ZZ20240531BLRHYD2811.0,2811.0,Boeing 717,05/31/2024,2024-05-31 14:16:00,2024-06-01 07:15:00,BLR,...,14,18,46,21,19,25,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
729,INV-ZZ-5606836,SCH-ZZ-4295870,ZZ,ZZ20240601BLRHYD2811.0,2811.0,Boeing 717,06/01/2024,2024-06-01 14:16:00,2024-06-02 07:15:00,BLR,...,14,18,45,21,19,24,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
730,INV-ZZ-5898356,SCH-ZZ-4295870,ZZ,ZZ20240604BLRHYD2811.0,2811.0,Boeing 717,06/04/2024,2024-06-04 14:16:00,2024-06-05 07:15:00,BLR,...,12,18,45,23,17,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
731,INV-ZZ-8814312,SCH-ZZ-4295870,ZZ,ZZ20240607BLRHYD2811.0,2811.0,Boeing 717,06/07/2024,2024-06-07 14:16:00,2024-06-08 07:15:00,BLR,...,12,17,45,23,17,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
732,INV-ZZ-1980882,SCH-ZZ-4295870,ZZ,ZZ20240608BLRHYD2811.0,2811.0,Boeing 717,06/08/2024,2024-06-08 14:16:00,2024-06-09 07:15:00,BLR,...,15,20,46,20,20,26,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
733,INV-ZZ-3521439,SCH-ZZ-4295870,ZZ,ZZ20240611BLRHYD2811.0,2811.0,Boeing 717,06/11/2024,2024-06-11 14:16:00,2024-06-12 07:15:00,BLR,...,13,18,44,21,19,23,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
734,INV-ZZ-7281166,SCH-ZZ-4295870,ZZ,ZZ20240614BLRHYD2811.0,2811.0,Boeing 717,06/14/2024,2024-06-14 14:16:00,2024-06-15 07:15:00,BLR,...,15,19,45,20,20,25,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
735,INV-ZZ-6119512,SCH-ZZ-4295870,ZZ,ZZ20240615BLRHYD2811.0,2811.0,Boeing 717,06/15/2024,2024-06-15 14:16:00,2024-06-16 07:15:00,BLR,...,14,18,47,22,18,25,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."

In [104]:
max_ETD_diff = 72
min_conn_diff = 1
max_conn_diff = 12

In [105]:
city_dict =  dict(zip(f['ArrivalAirport'], f['DepartureAirport']))
city_dict #THis is a dictionary with arrival city as key and departure city as value, useful for "back-propagation" when we see lists of connecting flights

{'HYD': 'CJB',
 'AMD': 'BOM',
 'MAA': 'GOI',
 'CCU': 'BOM',
 'BOM': 'GAU',
 'BLR': 'JAI',
 'DEL': 'JAI',
 'CJB': 'HYD',
 'TRV': 'MAA',
 'PNQ': 'GAU',
 'IDR': 'HYD',
 'LKO': 'JAI',
 'GAU': 'GOI',
 'GOI': 'PNQ'}

In [106]:
# Function to get City Mapping
city_mapping = {}

# Iterate over each row in the DataFrame
for index, row in f.iterrows():
    arrival_city = row['ArrivalAirport']
    departure_city = row['DepartureAirport']

    # Check if arrival city is already in the dictionary
    if arrival_city in city_mapping:
        # Append departure city to the existing list
        city_mapping[arrival_city].append(departure_city)
    else:
        # Create a new list for the arrival city
        city_mapping[arrival_city] = [departure_city]
for key in city_mapping.keys():
    city_mapping[key] = np.unique(city_mapping[key])

In [107]:
city_mapping

{'HYD': array(['AMD', 'BLR', 'BOM', 'CCU', 'CJB', 'IDR', 'MAA'], dtype='<U3'),
 'AMD': array(['BLR', 'BOM', 'DEL', 'HYD', 'MAA'], dtype='<U3'),
 'MAA': array(['AMD', 'BOM', 'CCU', 'DEL', 'GOI'], dtype='<U3'),
 'CCU': array(['AMD', 'BLR', 'BOM', 'HYD', 'MAA'], dtype='<U3'),
 'BOM': array(['AMD', 'BLR', 'CCU', 'DEL', 'GAU', 'GOI', 'MAA', 'PNQ'],
       dtype='<U3'),
 'BLR': array(['AMD', 'BBI', 'BOM', 'CCU', 'DEL', 'HYD', 'JAI', 'LKO'],
       dtype='<U3'),
 'DEL': array(['AMD', 'BLR', 'BOM', 'HYD', 'JAI'], dtype='<U3'),
 'CJB': array(['HYD', 'MAA'], dtype='<U3'),
 'TRV': array(['MAA'], dtype='<U3'),
 'PNQ': array(['BOM', 'GAU', 'GOI'], dtype='<U3'),
 'IDR': array(['HYD'], dtype='<U3'),
 'LKO': array(['JAI'], dtype='<U3'),
 'GAU': array(['GOI', 'PNQ'], dtype='<U3'),
 'GOI': array(['PNQ'], dtype='<U3')}

In [108]:
flight_details= pd.read_csv("/PNRB-ZZ-20231208_062017.csv")

In [109]:
flight_details

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ
0,DRGS80,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,3.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
1,YEZQ47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
2,JDDM40,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,3.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
3,AVFF16,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
4,DBLE79,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20189,HMHR27,1/1/2024 4:13,ZZ20240511BOMPNQ2977,GN,PremiumEconomyClass,2.0,3.0,6.0,ZZ,2977.0,BOM,PNQ,5/11/2024,5/11/2024 14:12,5/11/2024 16:17,5/11/2024 8:42,5/11/2024 10:47
20190,HMHR27,1/1/2024 4:13,ZZ20240513PNQGOI2738,HL,PremiumEconomyClass,3.0,3.0,6.0,ZZ,2738.0,PNQ,GOI,5/13/2024,5/13/2024 5:09,5/13/2024 17:37,5/12/2024 23:39,5/13/2024 12:07
20191,NBDF48,1/1/2024 4:13,ZZ20240509BOMHYD2933,HK,PremiumEconomyClass,2.0,2.0,5.0,ZZ,2933.0,BOM,HYD,5/9/2024,5/9/2024 14:57,5/9/2024 20:14,5/9/2024 9:27,5/9/2024 14:44
20192,BNUI98,1/1/2024 4:13,ZZ20240502BOMDEL2019,HL,PremiumEconomyClass,2.0,4.0,2.0,ZZ,2019.0,BOM,DEL,5/2/2024,5/2/2024 16:42,5/3/2024 4:40,5/2/2024 11:12,5/2/2024 23:10
20193,ODEU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
passenger= pd.read_csv("/PNRP-ZZ-20231208_111136.csv")

In [111]:
f.Dep_Key

0       ZZ20240505AMDHYD2223.0
1       ZZ20240506AMDHYD2223.0
2       ZZ20240507AMDHYD2223.0
3       ZZ20240508AMDHYD2223.0
4       ZZ20240512AMDHYD2223.0
                 ...
2007    ZZ20240617GAUPNQ3440.0
2008    ZZ20240620GAUPNQ3440.0
2009    ZZ20240621GAUPNQ3440.0
2010    ZZ20240623GAUPNQ3440.0
2011    ZZ20240624GAUPNQ3440.0
Name: Dep_Key, Length: 2012, dtype: object

In [112]:
specific_flight_number= 2504
filtered_f= flight_details[flight_details["FLT_NUM"]== specific_flight_number]

In [113]:
specific_dep_key= "ZZ20240403BLRCCU2504"
filtered_f= flight_details[flight_details["DEP_KEY"]== specific_dep_key]

In [114]:
# filtered_f
filtered_f_copy= filtered_f
filtered_f_copy

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ
0,DRGS80,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,3.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
1,YEZQ47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
2,JDDM40,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,3.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
3,AVFF16,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
4,DBLE79,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,WJIM84,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,6.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
78,GYKM90,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,2.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
79,JGYU67,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,1.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
80,OQHS47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
81,JMZZ69,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47

In [118]:
external_multiplier_seg = 100
external_multiplier_pax = 50

In [125]:
filtered_f_copy['SEG_TOTAL_MULTIPLIED'] = filtered_f_copy['SEG_TOTAL'] * external_multiplier_seg
filtered_f_copy['PAX_CNT_MULTIPLIED'] = filtered_f_copy['PAX_CNT'] * external_multiplier_pax

# Create a new column with the sum of SEG_SEQ_MULTIPLIED and PAX_CNT_MULTIPLIED
filtered_f_copy['SUM_SEG_PAX'] = filtered_f_copy['SEG_TOTAL_MULTIPLIED'] + filtered_f_copy['PAX_CNT_MULTIPLIED']

<ipython-input-125-7611df0424c7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_f_copy['SEG_TOTAL_MULTIPLIED'] = filtered_f_copy['SEG_TOTAL'] * external_multiplier_seg
<ipython-input-125-7611df0424c7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_f_copy['PAX_CNT_MULTIPLIED'] = filtered_f_copy['PAX_CNT'] * external_multiplier_pax
<ipython-input-125-7611df0424c7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_f_copy['SUM_SEG_PAX'] = filtered_f_copy['SEG_TOTAL_MULTIPLIED'] + filtered_f_copy['PAX_CNT_MULTIPLIED']

In [128]:
filtered_f_copy

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ,PAX_CNT_MULTIPLIED,SUM_SEG_PAX,SEG_TOTAL_MULTIPLIED
0,DRGS80,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,3.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,150.0,550.0,400.0
1,YEZQ47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,200.0,400.0,200.0
2,JDDM40,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,3.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,100.0,400.0,300.0
3,AVFF16,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,50.0,450.0,400.0
4,DBLE79,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1.0,2.0,2.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,100.0,300.0,200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,WJIM84,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,6.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,300.0,700.0,400.0
78,GYKM90,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,2.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,200.0,400.0,200.0
79,JGYU67,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,1.0,4.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,200.0,300.0,100.0
80,OQHS47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,50.0,450.0,400.0
81,JMZZ69,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,EconomyClass,1.0,4.0,1.0,ZZ,2504.0,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47,50.0,450.0,400.0

In [135]:
reclocs_list = filtered_f["RECLOC"].tolist()

In [151]:
filtered_passengers_list = passenger[passenger["RECLOC"].isin(reclocs_list)]
filtered_passengers_list

,RECLOC,CREATION_DTZ,CUSTOMER_ID,LAST_NAME,FIRST_NAME,NATIONALITY,DOB,CONTACT_PH_NUM,CONTACT_EMAIL,DOC_TYPE,DOC_ID,SPECIAL_NAME_CD2,SSR_CODE_CD1,SPECIAL_NAME_CD1,FF_NUM,TierLevel
0,DRGS80,3/2/2024 16:35,VNQ9748,Mitchell,Christina,CA,6/1/2003,1-769-506-8397,christinamitchell1@example.com,Driving License,2.991960e+11,NaN,NaN,ADT,4.276771e+09,Gold
1,DRGS80,3/2/2024 16:35,BAP1926,Parker,Rebecca,CA,8/18/2015,1-947-699-5143,rebeccaparker2@example.com,Passport,1.190198e+10,NaN,NaN,CHD,8.493470e+09,Platinum
2,DRGS80,3/2/2024 16:35,ALV9938,Swamy,Vardaniya,IN,2/23/1945,6102977873,vardaniyaswamy3@example.com,Govt-Id,4.283733e+09,NaN,NaN,S65,6.731611e+09,Platinum
3,YEZQ47,3/2/2024 16:35,CEU7075,Edwin,Stuvan,IN,6/18/2003,5791967032,stuvanedwin1@example.com,Passport,1.392676e+08,NaN,NaN,ADT,7.214819e+09,Platinum
4,YEZQ47,3/2/2024 16:35,WFG9647,Hernandez,Andrea,CA,7/3/1969,+1 (378) 291-0325,andreahernandez2@example.com,Govt-Id,5.459763e+09,NaN,NaN,ADT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,JGYU67,3/2/2024 16:35,BET1958,Bhavsar,Mishti,IN,12/24/1934,(297) 128-2827,mishtibhavsar2@example.com,Driving License,8.731830e+11,NaN,NaN,S65,NaN,NaN
290,JGYU67,3/2/2024 16:35,EAO0810,Mander,Divij,IN,1/15/1983,(974) 477-3582,divijmander3@example.com,Govt-Id,5.756797e+08,NaN,NaN,ADT,NaN,NaN
291,JGYU67,3/2/2024 16:35,NIY2672,Clarke,Scott,CA,4/25/2020,(458) 390-4173,scottclarke4@example.com,Passport,7.427225e+08,NaN,WCHR,INF,3.779364e+09,Gold
292,OQHS47,3/2/2024 16:35,AGT0811,Taylor,Amanda,CA,3/16/2022,(336) 748-1881,amandataylor1@example.com,Govt-Id,1.961622e+09,NaN,NaN,INS,1.317973e+09,Gold
293,JMZZ69,3/2/2024 16:35,HDO7890,Andrade,Christopher,CA,10/6/1949,(409) 684-4211,christopherandrade1@example.com,Govt-Id,5.101157e+09,NaN,NaN,S65,5.409102e+09,Platinum

In [152]:
tags_cost ={'INFT' : 200, 'WCHR' : 200, 'WCHS' : 200, 'WCHC' : 200, 'LANG' : 200, 'CHLD' : 200, 'MAAS' : 200, 'UNMR' : 200, 'BLND' : 200, 'DEAF' : 200, 'EXST' : 200, 'MEAL' : 200, 'NSST' : 200, 'NRPS' : 200,  }
loyalty_cost = {'Platinum' : 2200, 'Gold' : 2000, 'Silver' : 2000, 'none':0 }

In [156]:
tag_columns = ['SPECIAL_NAME_CD2', 'SSR_CODE_CD1']

In [163]:
filtered_passengers_list['ssr_score'] = filtered_passengers_list[tag_columns].applymap(tags_cost.get).sum(axis=1)

<ipython-input-163-1fb59be1f760>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['ssr_score'] = filtered_passengers_list[tag_columns].applymap(tags_cost.get).sum(axis=1)

In [164]:
filtered_passengers_list

,RECLOC,CREATION_DTZ,CUSTOMER_ID,LAST_NAME,FIRST_NAME,NATIONALITY,DOB,CONTACT_PH_NUM,CONTACT_EMAIL,DOC_TYPE,DOC_ID,SPECIAL_NAME_CD2,SSR_CODE_CD1,SPECIAL_NAME_CD1,FF_NUM,TierLevel,total_score,Loyalty_score,ssr_score
0,DRGS80,3/2/2024 16:35,VNQ9748,Mitchell,Christina,CA,6/1/2003,1-769-506-8397,christinamitchell1@example.com,Driving License,2.991960e+11,NaN,NaN,ADT,4.276771e+09,Gold,0.0,2000.0,0.0
1,DRGS80,3/2/2024 16:35,BAP1926,Parker,Rebecca,CA,8/18/2015,1-947-699-5143,rebeccaparker2@example.com,Passport,1.190198e+10,NaN,NaN,CHD,8.493470e+09,Platinum,0.0,2200.0,0.0
2,DRGS80,3/2/2024 16:35,ALV9938,Swamy,Vardaniya,IN,2/23/1945,6102977873,vardaniyaswamy3@example.com,Govt-Id,4.283733e+09,NaN,NaN,S65,6.731611e+09,Platinum,0.0,2200.0,0.0
3,YEZQ47,3/2/2024 16:35,CEU7075,Edwin,Stuvan,IN,6/18/2003,5791967032,stuvanedwin1@example.com,Passport,1.392676e+08,NaN,NaN,ADT,7.214819e+09,Platinum,0.0,2200.0,0.0
4,YEZQ47,3/2/2024 16:35,WFG9647,Hernandez,Andrea,CA,7/3/1969,+1 (378) 291-0325,andreahernandez2@example.com,Govt-Id,5.459763e+09,NaN,NaN,ADT,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,JGYU67,3/2/2024 16:35,BET1958,Bhavsar,Mishti,IN,12/24/1934,(297) 128-2827,mishtibhavsar2@example.com,Driving License,8.731830e+11,NaN,NaN,S65,NaN,NaN,0.0,0.0,0.0
290,JGYU67,3/2/2024 16:35,EAO0810,Mander,Divij,IN,1/15/1983,(974) 477-3582,divijmander3@example.com,Govt-Id,5.756797e+08,NaN,NaN,ADT,NaN,NaN,0.0,0.0,0.0
291,JGYU67,3/2/2024 16:35,NIY2672,Clarke,Scott,CA,4/25/2020,(458) 390-4173,scottclarke4@example.com,Passport,7.427225e+08,NaN,WCHR,INF,3.779364e+09,Gold,200.0,2000.0,200.0
292,OQHS47,3/2/2024 16:35,AGT0811,Taylor,Amanda,CA,3/16/2022,(336) 748-1881,amandataylor1@example.com,Govt-Id,1.961622e+09,NaN,NaN,INS,1.317973e+09,Gold,0.0,2000.0,0.0
293,JMZZ69,3/2/2024 16:35,HDO7890,Andrade,Christopher,CA,10/6/1949,(409) 684-4211,christopherandrade1@example.com,Govt-Id,5.101157e+09,NaN,NaN,S65,5.409102e+09,Platinum,0.0,2200.0,0.0

In [160]:

filtered_passengers_list['Loyalty_score'] = filtered_passengers_list['TierLevel'].map(loyalty_cost).fillna(loyalty_cost['none'])

<ipython-input-160-f281b22395ec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['Loyalty_score'] = filtered_passengers_list['TierLevel'].map(loyalty_cost).fillna(loyalty_cost['none'])

In [161]:
filtered_passengers_list

,RECLOC,CREATION_DTZ,CUSTOMER_ID,LAST_NAME,FIRST_NAME,NATIONALITY,DOB,CONTACT_PH_NUM,CONTACT_EMAIL,DOC_TYPE,DOC_ID,SPECIAL_NAME_CD2,SSR_CODE_CD1,SPECIAL_NAME_CD1,FF_NUM,TierLevel,total_score,Loyalty_score
0,DRGS80,3/2/2024 16:35,VNQ9748,Mitchell,Christina,CA,6/1/2003,1-769-506-8397,christinamitchell1@example.com,Driving License,2.991960e+11,NaN,NaN,ADT,4.276771e+09,Gold,0.0,2000.0
1,DRGS80,3/2/2024 16:35,BAP1926,Parker,Rebecca,CA,8/18/2015,1-947-699-5143,rebeccaparker2@example.com,Passport,1.190198e+10,NaN,NaN,CHD,8.493470e+09,Platinum,0.0,2200.0
2,DRGS80,3/2/2024 16:35,ALV9938,Swamy,Vardaniya,IN,2/23/1945,6102977873,vardaniyaswamy3@example.com,Govt-Id,4.283733e+09,NaN,NaN,S65,6.731611e+09,Platinum,0.0,2200.0
3,YEZQ47,3/2/2024 16:35,CEU7075,Edwin,Stuvan,IN,6/18/2003,5791967032,stuvanedwin1@example.com,Passport,1.392676e+08,NaN,NaN,ADT,7.214819e+09,Platinum,0.0,2200.0
4,YEZQ47,3/2/2024 16:35,WFG9647,Hernandez,Andrea,CA,7/3/1969,+1 (378) 291-0325,andreahernandez2@example.com,Govt-Id,5.459763e+09,NaN,NaN,ADT,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,JGYU67,3/2/2024 16:35,BET1958,Bhavsar,Mishti,IN,12/24/1934,(297) 128-2827,mishtibhavsar2@example.com,Driving License,8.731830e+11,NaN,NaN,S65,NaN,NaN,0.0,0.0
290,JGYU67,3/2/2024 16:35,EAO0810,Mander,Divij,IN,1/15/1983,(974) 477-3582,divijmander3@example.com,Govt-Id,5.756797e+08,NaN,NaN,ADT,NaN,NaN,0.0,0.0
291,JGYU67,3/2/2024 16:35,NIY2672,Clarke,Scott,CA,4/25/2020,(458) 390-4173,scottclarke4@example.com,Passport,7.427225e+08,NaN,WCHR,INF,3.779364e+09,Gold,200.0,2000.0
292,OQHS47,3/2/2024 16:35,AGT0811,Taylor,Amanda,CA,3/16/2022,(336) 748-1881,amandataylor1@example.com,Govt-Id,1.961622e+09,NaN,NaN,INS,1.317973e+09,Gold,0.0,2000.0
293,JMZZ69,3/2/2024 16:35,HDO7890,Andrade,Christopher,CA,10/6/1949,(409) 684-4211,christopherandrade1@example.com,Govt-Id,5.101157e+09,NaN,NaN,S65,5.409102e+09,Platinum,0.0,2200.0

In [165]:
filtered_passengers_list['Total_score'] = filtered_passengers_list['Loyalty_score'] + filtered_passengers_list['ssr_score']
sorted_passengers=filtered_passengers_list.sort_values(by="Total_score", ascending=False)

<ipython-input-165-a9f9f1a2f5b2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_passengers_list['Total_score'] = filtered_passengers_list['Loyalty_score'] + filtered_passengers_list['ssr_score']

In [153]:
# filtered_passengers_list_melted = filtered_passengers_list.melt(id_vars=['RECLOC', 'CUSTOMER_ID', 'TierLevel'], value_vars=['SPECIAL_NAME_CD2', 'SSR_CODE_CD1'], var_name='tag_num', value_name='tags')
# merged_passengers_cost = filtered_passengers_list_melted.merge(pd.DataFrame(list(tags_cost.items()), columns=['tags', 'cost']), on='tags', how='left')
# total_tags_costs = merged_passengers_cost.groupby(['RECLOC', 'CUSTOMER_ID', 'TierLevel'])['cost'].sum().reset_index()

In [154]:
# print(merged_passengers_cost)

In [155]:
# print(total_tags_costs)

     RECLOC CUSTOMER_ID TierLevel   cost
0    AMQB16     TPQ0077  Platinum    0.0
1    AVDY52     PUF6155    Silver    0.0
2    AVDY52     QKR2145    Silver    0.0
3    AVFF16     RLO9852    Silver    0.0
4    BCNL96     JBO2698  Platinum    0.0
..      ...         ...       ...    ...
161  ZZSK50     FQR1209      Gold    0.0
162  ZZSK50     GZS3171  Platinum    0.0
163  ZZSK50     JEO9973  Platinum    0.0
164  ZZSK50     MKL6478  Platinum  200.0
165  ZZSK50     SDS0210      Gold    0.0

[166 rows x 4 columns]

In [143]:
# total_loyalty_costs = total_tags_costs.groupby(['CUSTOMER_ID', 'TierLevel'])['cost'].sum().reset_index()

In [159]:

# total_tags_costs['Loyalty_score'] = total_tags_costs['TierLevel'].map(loyalty_cost).fillna(loyalty_cost['none'])

In [145]:
# total_tags_costs['TierLevel'].unique()

In [146]:
# print(total_tags_costs)

     RECLOC CUSTOMER_ID TierLevel   cost  Loyalty_score
0    AMQB16     TPQ0077  Platinum    0.0           2200
1    AVDY52     PUF6155    Silver    0.0           2000
2    AVDY52     QKR2145    Silver    0.0           2000
3    AVFF16     RLO9852    Silver    0.0           2000
4    BCNL96     JBO2698  Platinum    0.0           2200
..      ...         ...       ...    ...            ...
161  ZZSK50     FQR1209      Gold    0.0           2000
162  ZZSK50     GZS3171  Platinum    0.0           2200
163  ZZSK50     JEO9973  Platinum    0.0           2200
164  ZZSK50     MKL6478  Platinum  200.0           2200
165  ZZSK50     SDS0210      Gold    0.0           2000

[166 rows x 5 columns]

In [148]:
# total_tags_costs['Total_score'] = total_tags_costs['Loyalty_score'] + total_tags_costs['cost']

In [149]:
# sorted_passengers=total_tags_costs.sort_values(by="Total_score", ascending=False)

In [168]:
sorted_passengers

,RECLOC,CREATION_DTZ,CUSTOMER_ID,LAST_NAME,FIRST_NAME,NATIONALITY,DOB,CONTACT_PH_NUM,CONTACT_EMAIL,DOC_TYPE,DOC_ID,SPECIAL_NAME_CD2,SSR_CODE_CD1,SPECIAL_NAME_CD1,FF_NUM,TierLevel,total_score,Loyalty_score,ssr_score,Total_score
288,JGYU67,3/2/2024 16:35,YPD1979,Roy,Jayesh,IN,2/3/2020,(733) 611-1023,jayeshroy1@example.com,Passport,4.141344e+08,NRPS,WCHR,INF,1.139845e+09,Platinum,400.0,2200.0,400.0,2600.0
156,RXZR18,3/2/2024 16:35,CTV7902,Sherman,Dylan,CA,8/19/2022,(839) 442-5967,dylansherman5@example.com,Passport,6.564543e+08,NRPS,NaN,INS,7.355412e+09,Platinum,200.0,2200.0,200.0,2400.0
139,ICGG16,3/2/2024 16:35,AOA4855,Mand,Nishith,IN,10/13/1934,(297) 179-5264,nishithmand3@example.com,Driving License,9.916260e+11,NRPS,NaN,S65,9.654174e+09,Platinum,200.0,2200.0,200.0,2400.0
127,DGYQ98,3/2/2024 16:35,YQX4398,Wagner,Timothy,US,11/17/1973,(109) 806-3657,timothywagner3@example.com,Govt-Id,1.946722e+09,NaN,BLND,ADT,6.495359e+09,Platinum,200.0,2200.0,200.0,2400.0
222,ZZSK50,3/2/2024 16:35,MKL6478,Booth,Andrea,CA,10/18/1999,(998) 531-8235,andreabooth8@example.com,Passport,8.902865e+08,NaN,WCHR,ADT,5.686678e+09,Platinum,200.0,2200.0,200.0,2400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,XLXS10,3/2/2024 16:35,DZH4611,Norris,William,CA,10/15/1956,(795) 804-4352,williamnorris9@example.com,Passport,4.585767e+08,NaN,NaN,S65,NaN,NaN,0.0,0.0,0.0,0.0
117,EZNC46,3/2/2024 16:35,GUT1905,Krishnan,Yuvaan,IN,1/29/2010,(352) 247-3428,yuvaankrishnan3@example.com,Passport,3.696535e+07,NaN,NaN,CHD,NaN,NaN,0.0,0.0,0.0,0.0
28,POTO89,3/2/2024 16:35,CTL5491,Peters,William,CA,3/21/1980,(485) 852-2847,williampeters2@example.com,Driving License,4.644380e+11,NaN,NaN,ADT,NaN,NaN,0.0,0.0,0.0,0.0
119,EZNC46,3/2/2024 16:35,GWS7147,Kashyap,Divyansh,IN,2/6/1985,(668) 423-5407,divyanshkashyap5@example.com,Govt-Id,4.728697e+09,NRSA,NaN,ADT,NaN,NaN,0.0,0.0,0.0,0.0
61,QQHE41,3/2/2024 16:35,RMI0104,Norris,Michael,US,2/5/1967,(687) 460-9579,michaelnorris1@example.com,Passport,3.120335e+06,NaN,NaN,ADT,NaN,NaN,0.0,0.0,0.0,0.0